/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdminLoginResult = { 'success' : null } |
  { 'invalidCredentials' : null };
export interface AdminUserView {
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'phone' : Phone,
  'walletBalance' : Amount,
}
export type Amount = bigint;
export interface CommissionBuckets {
  'day' : Amount,
  'month' : Amount,
  'total' : Amount,
  'week' : Amount,
}
export interface CommissionDistribution {
  'level10' : [] | [Amount],
  'level1' : [] | [Amount],
  'level2' : [] | [Amount],
  'level3' : [] | [Amount],
  'level4' : [] | [Amount],
  'level5' : [] | [Amount],
  'level6' : [] | [Amount],
  'level7' : [] | [Amount],
  'level8' : [] | [Amount],
  'level9' : [] | [Amount],
}
export interface CommissionEntry {
  'userId' : Phone,
  'level' : bigint,
  'timestamp' : Timestamp,
  'fromUser' : Phone,
  'amount' : Amount,
}
export interface CommissionHistory {
  'commissionBuckets' : CommissionBuckets,
  'totalEarned' : Amount,
  'commissionLevels' : Array<CommissionEntry>,
  'lastCommission' : [] | [Amount],
  'activeDays' : bigint,
}
export interface ContactQuery {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Timestamp,
}
export interface CurrentMonthStats {
  'completedRecharges' : [] | [bigint],
  'createdAt' : Timestamp,
  'topEarners' : Array<TopEarner>,
  'referralStats' : [] | [
    {
      'totalReferrals' : bigint,
      'activeReferrals' : bigint,
      'topReferrers' : Array<TopReferrer>,
    }
  ],
  'commissionDistribution' : CommissionDistribution,
  'newUsers' : [] | [bigint],
}
export type DataPackOption = { 'gb1' : null } |
  { 'gb1_5PerDay' : null };
export type Phone = bigint;
export type RechargeOperator = { 'vi' : null } |
  { 'jio' : null } |
  { 'bsnl' : null } |
  { 'airtel' : null };
export interface RechargeRequest {
  'validity' : RechargeValidity,
  'status' : RechargeStatus,
  'adminAmount' : [] | [Amount],
  'userId' : Phone,
  'operator' : RechargeOperator,
  'mobileNumber' : bigint,
  'timestamp' : Timestamp,
  'dataPackOption' : [] | [DataPackOption],
}
export type RechargeStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type RechargeValidity = { 'days24' : null } |
  { 'days28' : null } |
  { 'dataPack' : null };
export type ReferralCode = string;
export interface RequestStatics {
  'latestUpdate' : [] | [Timestamp],
  'countResolved' : bigint,
  'updatedAt' : Timestamp,
  'countAll' : bigint,
  'countPending' : bigint,
}
export type Timestamp = bigint;
export interface TopEarner { 'userId' : Phone, 'amount' : Amount }
export interface TopReferrer { 'userId' : Phone, 'referralCount' : bigint }
export type UpiId = string;
export interface User {
  'referralCode' : string,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'referredBy' : [] | [ReferralCode],
  'upiId' : [] | [UpiId],
  'passwordHash' : string,
  'phone' : Phone,
  'walletBalance' : Amount,
}
export interface UserProfile {
  'displayName' : [] | [string],
  'upiId' : [] | [UpiId],
  'phone' : [] | [Phone],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UtrStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface UtrSubmission {
  'status' : UtrStatus,
  'userId' : Phone,
  'timestamp' : Timestamp,
  'utrNumber' : string,
}
export interface WithdrawalRequest {
  'status' : WithdrawalStatus,
  'userId' : Phone,
  'timestamp' : Timestamp,
  'upiId' : UpiId,
  'amount' : Amount,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminActivateUser' : ActorMethod<[Phone, Amount], Amount>,
  'adminGetAllUsers' : ActorMethod<[], Array<AdminUserView>>,
  'adminGetUserCount' : ActorMethod<[], bigint>,
  'adminLogin' : ActorMethod<[string, string], AdminLoginResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentAdmin' : ActorMethod<
    [],
    {
      'admin' : [[] | [User], Principal],
      'nextAdmin' : [] | [User],
      'currentActivationId' : [] | [User],
    }
  >,
  'getCurrentMonthStats' : ActorMethod<[], CurrentMonthStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'queryCommissionStats' : ActorMethod<[], Array<CommissionBuckets>>,
  'queryCommissions' : ActorMethod<[Phone], CommissionHistory>,
  'queryContactQueries' : ActorMethod<[], Array<ContactQuery>>,
  'queryRechargeRequests' : ActorMethod<
    [],
    { 'recharges' : Array<RechargeRequest>, 'totalAmount' : Amount }
  >,
  'queryRechargeRequestsRange' : ActorMethod<
    [Timestamp, Timestamp, [] | [boolean]],
    Array<RechargeRequest>
  >,
  'queryUTRSubmissions' : ActorMethod<[], Array<UtrSubmission>>,
  'queryUserStats' : ActorMethod<
    [Phone, [] | [Timestamp], bigint],
    { 'users' : Array<User>, 'commissions' : Array<CommissionEntry> }
  >,
  'queryWithdrawalRequests' : ActorMethod<
    [],
    { 'withdrawals' : Array<WithdrawalRequest>, 'users' : Array<User> }
  >,
  'queryWithdrawalRequestsRange' : ActorMethod<
    [Timestamp, Timestamp, [] | [boolean]],
    Array<WithdrawalRequest>
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'systemStats' : ActorMethod<
    [],
    {
      'withdrawStats' : Array<RequestStatics>,
      'rechargeStats' : Array<RequestStatics>,
    }
  >,
  'updateAdminCredentials' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];