/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Phone = IDL.Nat;
export const Amount = IDL.Nat;
export const Timestamp = IDL.Int;
export const AdminUserView = IDL.Record({
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'phone' : Phone,
  'walletBalance' : Amount,
});
export const AdminLoginResult = IDL.Variant({
  'success' : IDL.Null,
  'invalidCredentials' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UpiId = IDL.Text;
export const UserProfile = IDL.Record({
  'displayName' : IDL.Opt(IDL.Text),
  'upiId' : IDL.Opt(UpiId),
  'phone' : IDL.Opt(Phone),
});
export const ReferralCode = IDL.Text;
export const User = IDL.Record({
  'referralCode' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'referredBy' : IDL.Opt(ReferralCode),
  'upiId' : IDL.Opt(UpiId),
  'passwordHash' : IDL.Text,
  'phone' : Phone,
  'walletBalance' : Amount,
});
export const TopEarner = IDL.Record({ 'userId' : Phone, 'amount' : Amount });
export const TopReferrer = IDL.Record({
  'userId' : Phone,
  'referralCount' : IDL.Nat,
});
export const CommissionDistribution = IDL.Record({
  'level10' : IDL.Opt(Amount),
  'level1' : IDL.Opt(Amount),
  'level2' : IDL.Opt(Amount),
  'level3' : IDL.Opt(Amount),
  'level4' : IDL.Opt(Amount),
  'level5' : IDL.Opt(Amount),
  'level6' : IDL.Opt(Amount),
  'level7' : IDL.Opt(Amount),
  'level8' : IDL.Opt(Amount),
  'level9' : IDL.Opt(Amount),
});
export const CurrentMonthStats = IDL.Record({
  'completedRecharges' : IDL.Opt(IDL.Nat),
  'createdAt' : Timestamp,
  'topEarners' : IDL.Vec(TopEarner),
  'referralStats' : IDL.Opt(
    IDL.Record({
      'totalReferrals' : IDL.Nat,
      'activeReferrals' : IDL.Nat,
      'topReferrers' : IDL.Vec(TopReferrer),
    })
  ),
  'commissionDistribution' : CommissionDistribution,
  'newUsers' : IDL.Opt(IDL.Nat),
});
export const CommissionBuckets = IDL.Record({
  'day' : Amount,
  'month' : Amount,
  'total' : Amount,
  'week' : Amount,
});
export const CommissionEntry = IDL.Record({
  'userId' : Phone,
  'level' : IDL.Nat,
  'timestamp' : Timestamp,
  'fromUser' : Phone,
  'amount' : Amount,
});
export const CommissionHistory = IDL.Record({
  'commissionBuckets' : CommissionBuckets,
  'totalEarned' : Amount,
  'commissionLevels' : IDL.Vec(CommissionEntry),
  'lastCommission' : IDL.Opt(Amount),
  'activeDays' : IDL.Nat,
});
export const ContactQuery = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const RechargeValidity = IDL.Variant({
  'days24' : IDL.Null,
  'days28' : IDL.Null,
  'dataPack' : IDL.Null,
});
export const RechargeStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const RechargeOperator = IDL.Variant({
  'vi' : IDL.Null,
  'jio' : IDL.Null,
  'bsnl' : IDL.Null,
  'airtel' : IDL.Null,
});
export const DataPackOption = IDL.Variant({
  'gb1' : IDL.Null,
  'gb1_5PerDay' : IDL.Null,
});
export const RechargeRequest = IDL.Record({
  'validity' : RechargeValidity,
  'status' : RechargeStatus,
  'adminAmount' : IDL.Opt(Amount),
  'userId' : Phone,
  'operator' : RechargeOperator,
  'mobileNumber' : IDL.Nat,
  'timestamp' : Timestamp,
  'dataPackOption' : IDL.Opt(DataPackOption),
});
export const UtrStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UtrSubmission = IDL.Record({
  'status' : UtrStatus,
  'userId' : Phone,
  'timestamp' : Timestamp,
  'utrNumber' : IDL.Text,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawalRequest = IDL.Record({
  'status' : WithdrawalStatus,
  'userId' : Phone,
  'timestamp' : Timestamp,
  'upiId' : UpiId,
  'amount' : Amount,
});
export const RequestStatics = IDL.Record({
  'latestUpdate' : IDL.Opt(Timestamp),
  'countResolved' : IDL.Nat,
  'updatedAt' : Timestamp,
  'countAll' : IDL.Nat,
  'countPending' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminActivateUser' : IDL.Func([Phone, Amount], [Amount], []),
  'adminGetAllUsers' : IDL.Func([], [IDL.Vec(AdminUserView)], ['query']),
  'adminGetUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [AdminLoginResult], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentAdmin' : IDL.Func(
      [],
      [
        IDL.Record({
          'admin' : IDL.Tuple(IDL.Opt(User), IDL.Principal),
          'nextAdmin' : IDL.Opt(User),
          'currentActivationId' : IDL.Opt(User),
        }),
      ],
      ['query'],
    ),
  'getCurrentMonthStats' : IDL.Func([], [CurrentMonthStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'queryCommissionStats' : IDL.Func([], [IDL.Vec(CommissionBuckets)], []),
  'queryCommissions' : IDL.Func([Phone], [CommissionHistory], ['query']),
  'queryContactQueries' : IDL.Func([], [IDL.Vec(ContactQuery)], []),
  'queryRechargeRequests' : IDL.Func(
      [],
      [
        IDL.Record({
          'recharges' : IDL.Vec(RechargeRequest),
          'totalAmount' : Amount,
        }),
      ],
      [],
    ),
  'queryRechargeRequestsRange' : IDL.Func(
      [Timestamp, Timestamp, IDL.Opt(IDL.Bool)],
      [IDL.Vec(RechargeRequest)],
      [],
    ),
  'queryUTRSubmissions' : IDL.Func([], [IDL.Vec(UtrSubmission)], []),
  'queryUserStats' : IDL.Func(
      [Phone, IDL.Opt(Timestamp), IDL.Nat],
      [
        IDL.Record({
          'users' : IDL.Vec(User),
          'commissions' : IDL.Vec(CommissionEntry),
        }),
      ],
      [],
    ),
  'queryWithdrawalRequests' : IDL.Func(
      [],
      [
        IDL.Record({
          'withdrawals' : IDL.Vec(WithdrawalRequest),
          'users' : IDL.Vec(User),
        }),
      ],
      [],
    ),
  'queryWithdrawalRequestsRange' : IDL.Func(
      [Timestamp, Timestamp, IDL.Opt(IDL.Bool)],
      [IDL.Vec(WithdrawalRequest)],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'systemStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'withdrawStats' : IDL.Vec(RequestStatics),
          'rechargeStats' : IDL.Vec(RequestStatics),
        }),
      ],
      ['query'],
    ),
  'updateAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Phone = IDL.Nat;
  const Amount = IDL.Nat;
  const Timestamp = IDL.Int;
  const AdminUserView = IDL.Record({
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'phone' : Phone,
    'walletBalance' : Amount,
  });
  const AdminLoginResult = IDL.Variant({
    'success' : IDL.Null,
    'invalidCredentials' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UpiId = IDL.Text;
  const UserProfile = IDL.Record({
    'displayName' : IDL.Opt(IDL.Text),
    'upiId' : IDL.Opt(UpiId),
    'phone' : IDL.Opt(Phone),
  });
  const ReferralCode = IDL.Text;
  const User = IDL.Record({
    'referralCode' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'referredBy' : IDL.Opt(ReferralCode),
    'upiId' : IDL.Opt(UpiId),
    'passwordHash' : IDL.Text,
    'phone' : Phone,
    'walletBalance' : Amount,
  });
  const TopEarner = IDL.Record({ 'userId' : Phone, 'amount' : Amount });
  const TopReferrer = IDL.Record({
    'userId' : Phone,
    'referralCount' : IDL.Nat,
  });
  const CommissionDistribution = IDL.Record({
    'level10' : IDL.Opt(Amount),
    'level1' : IDL.Opt(Amount),
    'level2' : IDL.Opt(Amount),
    'level3' : IDL.Opt(Amount),
    'level4' : IDL.Opt(Amount),
    'level5' : IDL.Opt(Amount),
    'level6' : IDL.Opt(Amount),
    'level7' : IDL.Opt(Amount),
    'level8' : IDL.Opt(Amount),
    'level9' : IDL.Opt(Amount),
  });
  const CurrentMonthStats = IDL.Record({
    'completedRecharges' : IDL.Opt(IDL.Nat),
    'createdAt' : Timestamp,
    'topEarners' : IDL.Vec(TopEarner),
    'referralStats' : IDL.Opt(
      IDL.Record({
        'totalReferrals' : IDL.Nat,
        'activeReferrals' : IDL.Nat,
        'topReferrers' : IDL.Vec(TopReferrer),
      })
    ),
    'commissionDistribution' : CommissionDistribution,
    'newUsers' : IDL.Opt(IDL.Nat),
  });
  const CommissionBuckets = IDL.Record({
    'day' : Amount,
    'month' : Amount,
    'total' : Amount,
    'week' : Amount,
  });
  const CommissionEntry = IDL.Record({
    'userId' : Phone,
    'level' : IDL.Nat,
    'timestamp' : Timestamp,
    'fromUser' : Phone,
    'amount' : Amount,
  });
  const CommissionHistory = IDL.Record({
    'commissionBuckets' : CommissionBuckets,
    'totalEarned' : Amount,
    'commissionLevels' : IDL.Vec(CommissionEntry),
    'lastCommission' : IDL.Opt(Amount),
    'activeDays' : IDL.Nat,
  });
  const ContactQuery = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const RechargeValidity = IDL.Variant({
    'days24' : IDL.Null,
    'days28' : IDL.Null,
    'dataPack' : IDL.Null,
  });
  const RechargeStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const RechargeOperator = IDL.Variant({
    'vi' : IDL.Null,
    'jio' : IDL.Null,
    'bsnl' : IDL.Null,
    'airtel' : IDL.Null,
  });
  const DataPackOption = IDL.Variant({
    'gb1' : IDL.Null,
    'gb1_5PerDay' : IDL.Null,
  });
  const RechargeRequest = IDL.Record({
    'validity' : RechargeValidity,
    'status' : RechargeStatus,
    'adminAmount' : IDL.Opt(Amount),
    'userId' : Phone,
    'operator' : RechargeOperator,
    'mobileNumber' : IDL.Nat,
    'timestamp' : Timestamp,
    'dataPackOption' : IDL.Opt(DataPackOption),
  });
  const UtrStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UtrSubmission = IDL.Record({
    'status' : UtrStatus,
    'userId' : Phone,
    'timestamp' : Timestamp,
    'utrNumber' : IDL.Text,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawalRequest = IDL.Record({
    'status' : WithdrawalStatus,
    'userId' : Phone,
    'timestamp' : Timestamp,
    'upiId' : UpiId,
    'amount' : Amount,
  });
  const RequestStatics = IDL.Record({
    'latestUpdate' : IDL.Opt(Timestamp),
    'countResolved' : IDL.Nat,
    'updatedAt' : Timestamp,
    'countAll' : IDL.Nat,
    'countPending' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminActivateUser' : IDL.Func([Phone, Amount], [Amount], []),
    'adminGetAllUsers' : IDL.Func([], [IDL.Vec(AdminUserView)], ['query']),
    'adminGetUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'adminLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [AdminLoginResult],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentAdmin' : IDL.Func(
        [],
        [
          IDL.Record({
            'admin' : IDL.Tuple(IDL.Opt(User), IDL.Principal),
            'nextAdmin' : IDL.Opt(User),
            'currentActivationId' : IDL.Opt(User),
          }),
        ],
        ['query'],
      ),
    'getCurrentMonthStats' : IDL.Func([], [CurrentMonthStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'queryCommissionStats' : IDL.Func([], [IDL.Vec(CommissionBuckets)], []),
    'queryCommissions' : IDL.Func([Phone], [CommissionHistory], ['query']),
    'queryContactQueries' : IDL.Func([], [IDL.Vec(ContactQuery)], []),
    'queryRechargeRequests' : IDL.Func(
        [],
        [
          IDL.Record({
            'recharges' : IDL.Vec(RechargeRequest),
            'totalAmount' : Amount,
          }),
        ],
        [],
      ),
    'queryRechargeRequestsRange' : IDL.Func(
        [Timestamp, Timestamp, IDL.Opt(IDL.Bool)],
        [IDL.Vec(RechargeRequest)],
        [],
      ),
    'queryUTRSubmissions' : IDL.Func([], [IDL.Vec(UtrSubmission)], []),
    'queryUserStats' : IDL.Func(
        [Phone, IDL.Opt(Timestamp), IDL.Nat],
        [
          IDL.Record({
            'users' : IDL.Vec(User),
            'commissions' : IDL.Vec(CommissionEntry),
          }),
        ],
        [],
      ),
    'queryWithdrawalRequests' : IDL.Func(
        [],
        [
          IDL.Record({
            'withdrawals' : IDL.Vec(WithdrawalRequest),
            'users' : IDL.Vec(User),
          }),
        ],
        [],
      ),
    'queryWithdrawalRequestsRange' : IDL.Func(
        [Timestamp, Timestamp, IDL.Opt(IDL.Bool)],
        [IDL.Vec(WithdrawalRequest)],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'systemStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'withdrawStats' : IDL.Vec(RequestStatics),
            'rechargeStats' : IDL.Vec(RequestStatics),
          }),
        ],
        ['query'],
      ),
    'updateAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };