/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CommissionHistory {
    commissionBuckets: CommissionBuckets;
    totalEarned: Amount;
    commissionLevels: Array<CommissionEntry>;
    lastCommission?: Amount;
    activeDays: bigint;
}
export type Timestamp = bigint;
export interface RequestStatics {
    latestUpdate?: Timestamp;
    countResolved: bigint;
    updatedAt: Timestamp;
    countAll: bigint;
    countPending: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type Phone = bigint;
export interface CurrentMonthStats {
    completedRecharges?: bigint;
    createdAt: Timestamp;
    topEarners: Array<TopEarner>;
    referralStats?: {
        totalReferrals: bigint;
        activeReferrals: bigint;
        topReferrers: Array<TopReferrer>;
    };
    commissionDistribution: CommissionDistribution;
    newUsers?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CommissionDistribution {
    level10?: Amount;
    level1?: Amount;
    level2?: Amount;
    level3?: Amount;
    level4?: Amount;
    level5?: Amount;
    level6?: Amount;
    level7?: Amount;
    level8?: Amount;
    level9?: Amount;
}
export interface RechargeRequest {
    validity: RechargeValidity;
    status: RechargeStatus;
    adminAmount?: Amount;
    userId: Phone;
    operator: RechargeOperator;
    mobileNumber: bigint;
    timestamp: Timestamp;
    dataPackOption?: DataPackOption;
}
export interface UtrSubmission {
    status: UtrStatus;
    userId: Phone;
    timestamp: Timestamp;
    utrNumber: string;
}
export interface ContactQuery {
    name: string;
    email: string;
    message: string;
    timestamp: Timestamp;
}
export interface CommissionBuckets {
    day: Amount;
    month: Amount;
    total: Amount;
    week: Amount;
}
export type UpiId = string;
export interface User {
    referralCode: string;
    createdAt: Timestamp;
    isActive: boolean;
    referredBy?: ReferralCode;
    upiId?: UpiId;
    passwordHash: string;
    phone: Phone;
    walletBalance: Amount;
}
export type Amount = bigint;
export interface AdminUserView {
    createdAt: Timestamp;
    isActive: boolean;
    phone: Phone;
    walletBalance: Amount;
}
export interface TopEarner {
    userId: Phone;
    amount: Amount;
}
export interface TopReferrer {
    userId: Phone;
    referralCount: bigint;
}
export interface CommissionEntry {
    userId: Phone;
    level: bigint;
    timestamp: Timestamp;
    fromUser: Phone;
    amount: Amount;
}
export interface WithdrawalRequest {
    status: WithdrawalStatus;
    userId: Phone;
    timestamp: Timestamp;
    upiId: UpiId;
    amount: Amount;
}
export type ReferralCode = string;
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    displayName?: string;
    upiId?: UpiId;
    phone?: Phone;
}
export enum AdminLoginResult {
    success = "success",
    invalidCredentials = "invalidCredentials"
}
export enum DataPackOption {
    gb1 = "gb1",
    gb1_5PerDay = "gb1_5PerDay"
}
export enum RechargeOperator {
    vi = "vi",
    jio = "jio",
    bsnl = "bsnl",
    airtel = "airtel"
}
export enum RechargeStatus {
    cancelled = "cancelled",
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum RechargeValidity {
    days24 = "days24",
    days28 = "days28",
    dataPack = "dataPack"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UtrStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminActivateUser(userId: Phone, arg1: Amount): Promise<Amount>;
    adminGetAllUsers(): Promise<Array<AdminUserView>>;
    adminGetUserCount(): Promise<bigint>;
    adminLogin(username: string, password: string): Promise<AdminLoginResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentAdmin(): Promise<{
        admin: [User | null, Principal];
        nextAdmin?: User;
        currentActivationId?: User;
    }>;
    getCurrentMonthStats(): Promise<CurrentMonthStats>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    queryCommissionStats(): Promise<Array<CommissionBuckets>>;
    queryCommissions(phone: Phone): Promise<CommissionHistory>;
    queryContactQueries(): Promise<Array<ContactQuery>>;
    queryRechargeRequests(): Promise<{
        recharges: Array<RechargeRequest>;
        totalAmount: Amount;
    }>;
    queryRechargeRequestsRange(arg0: Timestamp, arg1: Timestamp, arg2: boolean | null): Promise<Array<RechargeRequest>>;
    queryUTRSubmissions(): Promise<Array<UtrSubmission>>;
    queryUserStats(arg0: Phone, arg1: Timestamp | null, arg2: bigint): Promise<{
        users: Array<User>;
        commissions: Array<CommissionEntry>;
    }>;
    queryWithdrawalRequests(): Promise<{
        withdrawals: Array<WithdrawalRequest>;
        users: Array<User>;
    }>;
    queryWithdrawalRequestsRange(arg0: Timestamp, arg1: Timestamp, arg2: boolean | null): Promise<Array<WithdrawalRequest>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    systemStats(): Promise<{
        withdrawStats: Array<RequestStatics>;
        rechargeStats: Array<RequestStatics>;
    }>;
    updateAdminCredentials(newUsername: string, newPassword: string): Promise<void>;
}
import type { AdminLoginResult as _AdminLoginResult, Amount as _Amount, CommissionBuckets as _CommissionBuckets, CommissionDistribution as _CommissionDistribution, CommissionEntry as _CommissionEntry, CommissionHistory as _CommissionHistory, CurrentMonthStats as _CurrentMonthStats, DataPackOption as _DataPackOption, Phone as _Phone, RechargeOperator as _RechargeOperator, RechargeRequest as _RechargeRequest, RechargeStatus as _RechargeStatus, RechargeValidity as _RechargeValidity, ReferralCode as _ReferralCode, RequestStatics as _RequestStatics, Timestamp as _Timestamp, TopEarner as _TopEarner, TopReferrer as _TopReferrer, UpiId as _UpiId, User as _User, UserProfile as _UserProfile, UserRole as _UserRole, UtrStatus as _UtrStatus, UtrSubmission as _UtrSubmission, WithdrawalRequest as _WithdrawalRequest, WithdrawalStatus as _WithdrawalStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminActivateUser(arg0: Phone, arg1: Amount): Promise<Amount> {
        if (this.processError) {
            try {
                const result = await this.actor.adminActivateUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminActivateUser(arg0, arg1);
            return result;
        }
    }
    async adminGetAllUsers(): Promise<Array<AdminUserView>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllUsers();
            return result;
        }
    }
    async adminGetUserCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserCount();
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<AdminLoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_AdminLoginResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_AdminLoginResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentAdmin(): Promise<{
        admin: [User | null, Principal];
        nextAdmin?: User;
        currentActivationId?: User;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentAdmin();
                return from_candid_record_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentAdmin();
            return from_candid_record_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentMonthStats(): Promise<CurrentMonthStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentMonthStats();
                return from_candid_CurrentMonthStats_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentMonthStats();
            return from_candid_CurrentMonthStats_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async queryCommissionStats(): Promise<Array<CommissionBuckets>> {
        if (this.processError) {
            try {
                const result = await this.actor.queryCommissionStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryCommissionStats();
            return result;
        }
    }
    async queryCommissions(arg0: Phone): Promise<CommissionHistory> {
        if (this.processError) {
            try {
                const result = await this.actor.queryCommissions(arg0);
                return from_candid_CommissionHistory_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryCommissions(arg0);
            return from_candid_CommissionHistory_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async queryContactQueries(): Promise<Array<ContactQuery>> {
        if (this.processError) {
            try {
                const result = await this.actor.queryContactQueries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryContactQueries();
            return result;
        }
    }
    async queryRechargeRequests(): Promise<{
        recharges: Array<RechargeRequest>;
        totalAmount: Amount;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.queryRechargeRequests();
                return from_candid_record_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryRechargeRequests();
            return from_candid_record_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async queryRechargeRequestsRange(arg0: Timestamp, arg1: Timestamp, arg2: boolean | null): Promise<Array<RechargeRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.queryRechargeRequestsRange(arg0, arg1, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryRechargeRequestsRange(arg0, arg1, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async queryUTRSubmissions(): Promise<Array<UtrSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.queryUTRSubmissions();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryUTRSubmissions();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async queryUserStats(arg0: Phone, arg1: Timestamp | null, arg2: bigint): Promise<{
        users: Array<User>;
        commissions: Array<CommissionEntry>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.queryUserStats(arg0, to_candid_opt_n53(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_record_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryUserStats(arg0, to_candid_opt_n53(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_record_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async queryWithdrawalRequests(): Promise<{
        withdrawals: Array<WithdrawalRequest>;
        users: Array<User>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.queryWithdrawalRequests();
                return from_candid_record_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryWithdrawalRequests();
            return from_candid_record_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async queryWithdrawalRequestsRange(arg0: Timestamp, arg1: Timestamp, arg2: boolean | null): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.queryWithdrawalRequestsRange(arg0, arg1, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryWithdrawalRequestsRange(arg0, arg1, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n61(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n61(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async systemStats(): Promise<{
        withdrawStats: Array<RequestStatics>;
        rechargeStats: Array<RequestStatics>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.systemStats();
                return from_candid_record_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.systemStats();
            return from_candid_record_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAdminCredentials(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminCredentials(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AdminLoginResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminLoginResult): AdminLoginResult {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_CommissionDistribution_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommissionDistribution): CommissionDistribution {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_CommissionHistory_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommissionHistory): CommissionHistory {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_CurrentMonthStats_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CurrentMonthStats): CurrentMonthStats {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_DataPackOption_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DataPackOption): DataPackOption {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_RechargeOperator_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RechargeOperator): RechargeOperator {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_RechargeRequest_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RechargeRequest): RechargeRequest {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_RechargeStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RechargeStatus): RechargeStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_RechargeValidity_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RechargeValidity): RechargeValidity {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatics_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatics): RequestStatics {
    return from_candid_record_n66(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_User_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UtrStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UtrStatus): UtrStatus {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_UtrSubmission_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UtrSubmission): UtrSubmission {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequest_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequest): WithdrawalRequest {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UpiId]): UpiId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Phone]): Phone | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReferralCode]): ReferralCode | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        totalReferrals: bigint;
        activeReferrals: bigint;
        topReferrers: Array<_TopReferrer>;
    }]): {
    totalReferrals: bigint;
    activeReferrals: bigint;
    topReferrers: Array<TopReferrer>;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Amount]): Amount | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DataPackOption]): DataPackOption | null {
    return value.length === 0 ? null : from_candid_DataPackOption_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: [] | [string];
    upiId: [] | [_UpiId];
    phone: [] | [_Phone];
}): {
    displayName?: string;
    upiId?: UpiId;
    phone?: Phone;
} {
    return {
        displayName: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.displayName)),
        upiId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.upiId)),
        phone: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: [[] | [_User], Principal];
    nextAdmin: [] | [_User];
    currentActivationId: [] | [_User];
}): {
    admin: [User | null, Principal];
    nextAdmin?: User;
    currentActivationId?: User;
} {
    return {
        admin: from_candid_tuple_n21(_uploadFile, _downloadFile, value.admin),
        nextAdmin: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.nextAdmin)),
        currentActivationId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.currentActivationId))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: string;
    createdAt: _Timestamp;
    isActive: boolean;
    referredBy: [] | [_ReferralCode];
    upiId: [] | [_UpiId];
    passwordHash: string;
    phone: _Phone;
    walletBalance: _Amount;
}): {
    referralCode: string;
    createdAt: Timestamp;
    isActive: boolean;
    referredBy?: ReferralCode;
    upiId?: UpiId;
    passwordHash: string;
    phone: Phone;
    walletBalance: Amount;
} {
    return {
        referralCode: value.referralCode,
        createdAt: value.createdAt,
        isActive: value.isActive,
        referredBy: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.referredBy)),
        upiId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.upiId)),
        passwordHash: value.passwordHash,
        phone: value.phone,
        walletBalance: value.walletBalance
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedRecharges: [] | [bigint];
    createdAt: _Timestamp;
    topEarners: Array<_TopEarner>;
    referralStats: [] | [{
            totalReferrals: bigint;
            activeReferrals: bigint;
            topReferrers: Array<_TopReferrer>;
        }];
    commissionDistribution: _CommissionDistribution;
    newUsers: [] | [bigint];
}): {
    completedRecharges?: bigint;
    createdAt: Timestamp;
    topEarners: Array<TopEarner>;
    referralStats?: {
        totalReferrals: bigint;
        activeReferrals: bigint;
        topReferrers: Array<TopReferrer>;
    };
    commissionDistribution: CommissionDistribution;
    newUsers?: bigint;
} {
    return {
        completedRecharges: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.completedRecharges)),
        createdAt: value.createdAt,
        topEarners: value.topEarners,
        referralStats: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.referralStats)),
        commissionDistribution: from_candid_CommissionDistribution_n29(_uploadFile, _downloadFile, value.commissionDistribution),
        newUsers: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.newUsers))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    level10: [] | [_Amount];
    level1: [] | [_Amount];
    level2: [] | [_Amount];
    level3: [] | [_Amount];
    level4: [] | [_Amount];
    level5: [] | [_Amount];
    level6: [] | [_Amount];
    level7: [] | [_Amount];
    level8: [] | [_Amount];
    level9: [] | [_Amount];
}): {
    level10?: Amount;
    level1?: Amount;
    level2?: Amount;
    level3?: Amount;
    level4?: Amount;
    level5?: Amount;
    level6?: Amount;
    level7?: Amount;
    level8?: Amount;
    level9?: Amount;
} {
    return {
        level10: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.level10)),
        level1: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.level1)),
        level2: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.level2)),
        level3: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.level3)),
        level4: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.level4)),
        level5: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.level5)),
        level6: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.level6)),
        level7: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.level7)),
        level8: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.level8)),
        level9: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.level9))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    commissionBuckets: _CommissionBuckets;
    totalEarned: _Amount;
    commissionLevels: Array<_CommissionEntry>;
    lastCommission: [] | [_Amount];
    activeDays: bigint;
}): {
    commissionBuckets: CommissionBuckets;
    totalEarned: Amount;
    commissionLevels: Array<CommissionEntry>;
    lastCommission?: Amount;
    activeDays: bigint;
} {
    return {
        commissionBuckets: value.commissionBuckets,
        totalEarned: value.totalEarned,
        commissionLevels: value.commissionLevels,
        lastCommission: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.lastCommission)),
        activeDays: value.activeDays
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recharges: Array<_RechargeRequest>;
    totalAmount: _Amount;
}): {
    recharges: Array<RechargeRequest>;
    totalAmount: Amount;
} {
    return {
        recharges: from_candid_vec_n35(_uploadFile, _downloadFile, value.recharges),
        totalAmount: value.totalAmount
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    validity: _RechargeValidity;
    status: _RechargeStatus;
    adminAmount: [] | [_Amount];
    userId: _Phone;
    operator: _RechargeOperator;
    mobileNumber: bigint;
    timestamp: _Timestamp;
    dataPackOption: [] | [_DataPackOption];
}): {
    validity: RechargeValidity;
    status: RechargeStatus;
    adminAmount?: Amount;
    userId: Phone;
    operator: RechargeOperator;
    mobileNumber: bigint;
    timestamp: Timestamp;
    dataPackOption?: DataPackOption;
} {
    return {
        validity: from_candid_RechargeValidity_n38(_uploadFile, _downloadFile, value.validity),
        status: from_candid_RechargeStatus_n40(_uploadFile, _downloadFile, value.status),
        adminAmount: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.adminAmount)),
        userId: value.userId,
        operator: from_candid_RechargeOperator_n42(_uploadFile, _downloadFile, value.operator),
        mobileNumber: value.mobileNumber,
        timestamp: value.timestamp,
        dataPackOption: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.dataPackOption))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _UtrStatus;
    userId: _Phone;
    timestamp: _Timestamp;
    utrNumber: string;
}): {
    status: UtrStatus;
    userId: Phone;
    timestamp: Timestamp;
    utrNumber: string;
} {
    return {
        status: from_candid_UtrStatus_n51(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        timestamp: value.timestamp,
        utrNumber: value.utrNumber
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    users: Array<_User>;
    commissions: Array<_CommissionEntry>;
}): {
    users: Array<User>;
    commissions: Array<CommissionEntry>;
} {
    return {
        users: from_candid_vec_n55(_uploadFile, _downloadFile, value.users),
        commissions: value.commissions
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    withdrawals: Array<_WithdrawalRequest>;
    users: Array<_User>;
}): {
    withdrawals: Array<WithdrawalRequest>;
    users: Array<User>;
} {
    return {
        withdrawals: from_candid_vec_n57(_uploadFile, _downloadFile, value.withdrawals),
        users: from_candid_vec_n55(_uploadFile, _downloadFile, value.users)
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _WithdrawalStatus;
    userId: _Phone;
    timestamp: _Timestamp;
    upiId: _UpiId;
    amount: _Amount;
}): {
    status: WithdrawalStatus;
    userId: Phone;
    timestamp: Timestamp;
    upiId: UpiId;
    amount: Amount;
} {
    return {
        status: from_candid_WithdrawalStatus_n60(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        timestamp: value.timestamp,
        upiId: value.upiId,
        amount: value.amount
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    withdrawStats: Array<_RequestStatics>;
    rechargeStats: Array<_RequestStatics>;
}): {
    withdrawStats: Array<RequestStatics>;
    rechargeStats: Array<RequestStatics>;
} {
    return {
        withdrawStats: from_candid_vec_n64(_uploadFile, _downloadFile, value.withdrawStats),
        rechargeStats: from_candid_vec_n64(_uploadFile, _downloadFile, value.rechargeStats)
    };
}
function from_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latestUpdate: [] | [_Timestamp];
    countResolved: bigint;
    updatedAt: _Timestamp;
    countAll: bigint;
    countPending: bigint;
}): {
    latestUpdate?: Timestamp;
    countResolved: bigint;
    updatedAt: Timestamp;
    countAll: bigint;
    countPending: bigint;
} {
    return {
        latestUpdate: record_opt_to_undefined(from_candid_opt_n67(_uploadFile, _downloadFile, value.latestUpdate)),
        countResolved: value.countResolved,
        updatedAt: value.updatedAt,
        countAll: value.countAll,
        countPending: value.countPending
    };
}
function from_candid_tuple_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [[] | [_User], Principal]): [User | null, Principal] {
    return [
        from_candid_opt_n22(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    days24: null;
} | {
    days28: null;
} | {
    dataPack: null;
}): RechargeValidity {
    return "days24" in value ? RechargeValidity.days24 : "days28" in value ? RechargeValidity.days28 : "dataPack" in value ? RechargeValidity.dataPack : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): RechargeStatus {
    return "cancelled" in value ? RechargeStatus.cancelled : "pending" in value ? RechargeStatus.pending : "approved" in value ? RechargeStatus.approved : "rejected" in value ? RechargeStatus.rejected : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vi: null;
} | {
    jio: null;
} | {
    bsnl: null;
} | {
    airtel: null;
}): RechargeOperator {
    return "vi" in value ? RechargeOperator.vi : "jio" in value ? RechargeOperator.jio : "bsnl" in value ? RechargeOperator.bsnl : "airtel" in value ? RechargeOperator.airtel : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gb1: null;
} | {
    gb1_5PerDay: null;
}): DataPackOption {
    return "gb1" in value ? DataPackOption.gb1 : "gb1_5PerDay" in value ? DataPackOption.gb1_5PerDay : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): UtrStatus {
    return "pending" in value ? UtrStatus.pending : "approved" in value ? UtrStatus.approved : "rejected" in value ? UtrStatus.rejected : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: null;
} | {
    invalidCredentials: null;
}): AdminLoginResult {
    return "success" in value ? AdminLoginResult.success : "invalidCredentials" in value ? AdminLoginResult.invalidCredentials : value;
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RechargeRequest>): Array<RechargeRequest> {
    return value.map((x)=>from_candid_RechargeRequest_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UtrSubmission>): Array<UtrSubmission> {
    return value.map((x)=>from_candid_UtrSubmission_n49(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequest>): Array<WithdrawalRequest> {
    return value.map((x)=>from_candid_WithdrawalRequest_n58(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RequestStatics>): Array<RequestStatics> {
    return value.map((x)=>from_candid_RequestStatics_n65(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n62(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName?: string;
    upiId?: UpiId;
    phone?: Phone;
}): {
    displayName: [] | [string];
    upiId: [] | [_UpiId];
    phone: [] | [_Phone];
} {
    return {
        displayName: value.displayName ? candid_some(value.displayName) : candid_none(),
        upiId: value.upiId ? candid_some(value.upiId) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
